plot(1:12, avg_low_f/max(avg_low_f),1:12, avg_high_f/max(avg_high_f), ...
1:12, avg_precip_in/max(avg_precip_in),1:12, days_w_precip/max(days_w_precip), ...
1:12, hrs_sun/max(hrs_sun))
title('Baltimore Weather')
legend('Average Low Temperature (F)', 'Average High Temperature (F)', 'Average Precipitation (inches)',...
    'Days With Precipitation', 'Hours of Sun', 'Location','SouthEast')